### ISSUE TITLE
Transfer to organization

### ISSUE THREAD

**Issue by hogelog** [teamdmemo/dmemo#275]
Currently I am not actively maintaining it, while @ragi256 is very actively maintaining it.

I think I'm going to transfer it to organization, because it's difficult to maintain in a personal repository because of its limited permissions.

@ragi256 What do you think?

**Comment by ragi256** [comment]
Thanks for the suggestion, hogelog.

I also skipped maintenance for a long time due to business schedule reasons. During that time, many gems needed to be updated, and I had a hard time restarting the development this time.
I would be grateful if it could be organized and made easier for other developers to join.

It would be good if you could nominate members based on their current merge rights.

**Comment by hogelog** [comment]
I transfered this repo to https://github.com/teamdmemo/dmemo and sent invitations.

I sent an owner invitation to @ragi256 and member invitatations to the rest.
